#!/bin/sh
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
cat <<!

Boot took $(cut -d' ' -f1 /proc/uptime) seconds


$(cat<< "EOF"

     _____           _
    |  __ \         | |
    | |__) ____  ___| | ___ __ ___   __ _ _ __  ___
    |  ___/ _` |/ __| |/ | '_ ` _ \ / _` | '_ \/ __|
    | |  | (_| | (__|   <| | | | | | (_| | | | \__ \
    |_|   \__,_|\___|_|\_|_| |_| |_|\__,_|_| |_|___/


      /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
     /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
    / /\/\ \ | | | | | / /__| | | | | |_| |>  <
    \/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\

EOF
)

Welcome to packmans_mini_linux


!
exec /bin/sh